### ISSUE TITLE
Select inputs not working for color selection

### ISSUE THREAD

**Issue by girlsam** [w3cj/materialize-themes#1]
Color options don't seem to be populating on your deployed site. I've attached a screenshot of the error.

<img width="790" alt="screen shot 2016-11-10 at 9 51 46 am" src="https://cloud.githubusercontent.com/assets/4448430/20186050/ad248840-a72b-11e6-81d9-27bb2da761b8.png">

**Comment by w3cj** [comment]
Hmm. What browser are you using? Can you take a screen cap of any errors in the dev tools as well?

**Comment by w3cj** [comment]
Fixed! Didn't realize `element.append()` was only supported in certain browsers. 

https://github.com/w3cj/materialize-themes/commit/fb18dfcd6801db64534ed82218c8efcbf3ad3c9a

Let me know if you have any more issues.

**Comment by girlsam** [comment]
Yep, it's working now! (I was in Chrome, btw).
